version: "3.9"

services:
  api:
    build: .
    container_name: market-research-api
    network_mode: host
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8085
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - ./reports:/app/reports
    depends_on:
      - redis
    command: ["python", "-u", "server.py"]

  agent-ui:
    build: ./agent-ui
    container_name: market-research-ui
    network_mode: host
    environment:
      - API_URL=http://localhost:8085
      - REDIS_URL=redis://localhost:6379/0
      # Configure undici timeouts via Node.js options
      - NODE_OPTIONS=--max-http-header-size=32768
    volumes:
      - ./agent-ui:/app
      - /app/node_modules
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    container_name: market-research-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis_data:
