version: "3.9"

services:
  api:
    build: .
    container_name: market-research-api
    network_mode: host
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8085
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - ./reports:/app/reports
    depends_on:
      - redis
    command: ["python", "-u", "server.py"]

  agent-ui:
    build: ./agent-ui
    container_name: market-research-ui
    network_mode: host
    volumes:
      - ./agent-ui:/app
      - /app/node_modules
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    container_name: market-research-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
