version: "3.9"

services:
  veratheon-research:
    build: .
    container_name: veratheon-research
    network_mode: host
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    volumes:
      - ./reports:/app/reports
    command: ["python", "-u", "server.py"]

  veratheon-ui:
    build: ../veratheon-ui
    container_name: veratheon-ui
    network_mode: host
    environment:
      - API_URL=http://localhost:8085
      # Configure undici timeouts for long-running requests
      - UNDICI_HEADERS_TIMEOUT=3600000
      - UNDICI_BODY_TIMEOUT=3600000
      - UNDICI_CONNECT_TIMEOUT=30000
      - NODE_OPTIONS=--max-http-header-size=32768
    volumes:
      - ../veratheon-ui:/app
      - /app/node_modules
    depends_on:
      - veratheon-research
