# prefect.toml
api.url                      = "http://127.0.0.1:4200/api"
ui.url                       = "http://127.0.0.1:4200"

# Disable the fallback ephemeral server
server.ephemeral.enabled     = false


results.persist_by_default = true